enable-module-update = true


#Morphe
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
build-mode = "apk"
rv-brand = "Morphe-dev"
version = "21.10.493"
included-patches = "'Change package name'"
patcher-args = "-e 'Change package name' -OpackageName=com.kugou.viper"
